Region: ap-southeast-1
Image:
  Os: ubuntu2004
SharedStorage:
  - MountDir: /shared
    Name: gaohn-efs
    StorageType: Efs
    EfsSettings:
      PerformanceMode: generalPurpose
      ThroughputMode: bursting
HeadNode:
  InstanceType: t2.micro
  Networking:
    SubnetId: subnet-02cc9a3a21eecdc77
  Ssh:
    KeyName: awsec2
Scheduling:
  Scheduler: slurm
  SlurmQueues:
  - Name: distributed-queue
    ComputeResources:
    - Name: g4dn2xlarge
      Instances:
      - InstanceType: g4dn.2xlarge
      MinCount: 2
      MaxCount: 2
    Networking:
      SubnetIds:
      - subnet-07a5d3d3f8c8f1a92
