Region: ap-southeast-1
Image:
  Os: ubuntu2004
HeadNode:
  InstanceType: t2.small
  Networking:
    SubnetId: subnet-0a0808f3709d18152
  Ssh:
    KeyName: awsec2
Scheduling:
  Scheduler: slurm
  SlurmQueues:
  - Name: distributed-queue
    ComputeResources:
    - Name: g4dnxlarge
      Instances:
      - InstanceType: g4dn.xlarge
      MinCount: 2
      MaxCount: 2
    Networking:
      SubnetIds:
      - subnet-063a7f685a5bbc0ef
