defaults:
  - _self_
  - model: base
  - datamodule: base
  - transform: base
  - stores: base
  - optimizer: base

train:
  num_classes: 10
  device: "cpu"
  project_name: "cifar10"
  debug: true
  seed: 1992
  num_epochs: 3

hydra:
  run:
    dir: "${stores.model_artifacts_dir}/${train.project_name}/${stores.unique_id}" # in sync with stores
