name:
  type: str
  description: The user's full name

age:
  type: int
  optional: false
  default: null
  description: The user's age in years

address:
  type: object
  properties:
    street:
      type: str
      description: Street name and number
    city:
      type: str
      description: City name
    postal_code:
      type: int
      description: Postal code or ZIP code
  description: The user's mailing address
  optional: true

phone_numbers:
  type: List[str]
  description: List of user's phone numbers

tags:
  type: List[object]
  items:
    properties:
      name:
        type: str
        description: Tag name
      value:
        type: int
        description: Tag value
  description: List of user tags

pet:
  type: object
  properties:
    name:
      type: str
      description: Pet name
    age:
      type: int
      description: Pet age in years
  description: User's pet