name: nvidia-docker

on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
        description: "Path to the Dockerfile to build"
      image:
        required: true
        type: string
        description: "Name of the image to build"

env:
  LATEST_TAG: ${{ inputs.image }}:latest

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set docker tag
      env:
        VERSION: ${{ env.LATEST_GIT_TAG }}
      run: |
        echo "VERSION_TAG=${{ inputs.image }}:${GITHUB_SHA::8}" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker # FIXME: https://github.com/docker/build-push-action/issues/892

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }} # repo name
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        # We can only build for the intersection of platforms supported by
        # QEMU and base python image, for now build only for
        # linux/amd64 and linux/arm64
        platforms: linux/amd64 # FIXME: multibuild not allowed if I specify drivert o be docker,linux/arm64
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.VERSION_TAG }}
        push: true