# Reference: https://github.com/langchain-ai/langchain/blob/master/.github/workflows/_release_docker.yml

name: release-docker

on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
        description: "Path to the Dockerfile to build"
      image:
        required: true
        type: string
        description: "Name of the image to build"

env:
  TEST_TAG: ${{ inputs.image }}:test
  LATEST_TAG: ${{ inputs.image }}:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get git tag
        id: get-latest-git-tag
        run: |
          echo "LATEST_GIT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
      - name: Set docker tag
        env:
          VERSION: ${{ env.LATEST_GIT_TAG }}
        run: |
          echo "VERSION_TAG=${{ inputs.image }}:${VERSION#v}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker # FIXME: https://github.com/docker/build-push-action/issues/892
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # repo name
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build for Test
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }} python -c "import omnivault"
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          # We can only build for the intersection of platforms supported by
          # QEMU and base python image, for now build only for
          # linux/amd64 and linux/arm64
          platforms: linux/amd64 # FIXME: multibuild not allowed if I specify drivert o be docker,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.LATEST_TAG }},${{ secrets.DOCKERHUB_USERNAME }}/${{ env.VERSION_TAG }}
          push: true