name: continuous-integration-continuous-deployment-jupyterbook

on:
  push:  # Trigger the workflow on push to main branch
    branches:
      - main

env:
  CONTENT_DIR: omniverse # the directory where the book's content is stored
  WEBSITE: www.gaohongnan.com
  UV_FROZEN: "1"

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  # Run CI checks first
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #     - name: Setup uv
  #       uses: astral-sh/setup-uv@v6
  #       with:
  #         enable-cache: true
  #     - name: Install dependencies
  #       run: make sync
  #     - name: Run lint
  #       run: make lint

  # security:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #     - name: Setup uv
  #       uses: astral-sh/setup-uv@v6
  #       with:
  #         enable-cache: true
  #     - name: Install dependencies
  #       run: make sync
  #     - name: Run security checks
  #       run: make security

  # typecheck:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #     - name: Setup uv
  #       uses: astral-sh/setup-uv@v6
  #       with:
  #         enable-cache: true
  #     - name: Install dependencies
  #       run: make sync
  #     - name: Run typecheck
  #       run: make typecheck

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #     - name: Setup uv
  #       uses: astral-sh/setup-uv@v6
  #       with:
  #         enable-cache: true
  #     - name: Install dependencies
  #       run: make sync
  #     - name: Run tests
  #       run: make test

  # coverage:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #     - name: Setup uv
  #       uses: astral-sh/setup-uv@v6
  #       with:
  #         enable-cache: true
  #     - name: Install dependencies
  #       run: make sync
  #     - name: Run tests with coverage
  #       run: make coverage

  build-and-deploy-book:
    name: Build and Deploy JupyterBook to GitHub Pages
    runs-on: ubuntu-latest
    # needs: [lint, security, typecheck, test, coverage] # need this since we run CI first before CD
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install dependencies
        run: make sync
      - name: Build the book
        run: |
          uv run jupyter-book build ${{ env.CONTENT_DIR }}
      - name: GitHub Pages action # Deploy the book's HTML to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.CONTENT_DIR }}/_build/html # Use environment variable
          cname: ${{ env.WEBSITE }}